packages:
  - .
  - ./platform
  - ./example/client

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  '@types/react': '>=19.2.2'
  '@types/react-dom': '>=19.2.2'
  axios@=1.10.0: '>=1.11.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  jsondiffpatch@<0.7.2: '>=0.7.2'
