packages:
  - pulumi-start-aws
  - s3-bucket

allowBuilds:
  '@pulumi/docker': false
  '@pulumi/docker-build': false
  esbuild: false
  protobufjs: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - pnpm@12.8.1

overrides:
  '@types/react': '>=19.2.2'
  '@types/react-dom': '>=19.2.2'
  axios@=1.10.0: '>=1.11.0'
  brace-expansion@<1.1.21: ^1.1.21
  brace-expansion@>=4.0.0 <5.0.12: ^5.0.12
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  ip-address@<=10.7.0: ^10.7.1
  jsondiffpatch@<0.7.2: '>=0.7.2'
