packages:
  - pulumi-start-aws
  - s3-bucket

allowBuilds:
  '@pulumi/docker': false
  '@pulumi/docker-build': false
  esbuild: false
  protobufjs: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - pnpm@12.9.0
  - http-cache-semantics@4.3.0

overrides:
  http-cache-semantics@<=4.2.0: ^4.3.0
